### ISSUE TITLE
Something about graphflow

### ISSUE THREAD

**Issue by Edison0521** [RapidsAtHKUST/ContinuousSubgraphMatching#1]
Hello Thank for this great job, I have a problem when I implementation the code, where can I get the map between querygraph and datagraph?,for exapmle  in graphflow.cpp line 245,the m[u]=v is a vertex mapping. but it seems not the mapping result form sourcedata,
chould you please help me to find it?

**Comment by xibosun** [comment]
Hi, the code does not explicitly store the set of all mappings from the query graph to the data graph. But one can run the code with `--print-enum on` to print all the mappings to the console.

**Comment by Edison0521** [comment]
> Hi, the code does not explicitly store the set of all mappings from the query graph to the data graph. But one can run the code with `--print-enum on` to print all the mappings to the console.

Thank you for your reply , That's would be great

**Comment by Edison0521** [comment]
> Hi, the code does not explicitly store the set of all mappings from the query graph to the data graph. But one can run the code with `--print-enum on` to print all the mappings to the console.

Hi, could you please look after my test example ,I think here are something confused in it,
My query graph is 
v 0 1
v 1 0
v 2 0
e 0 1 0
e 2 0 0
and data graph is
v 0 0
v 1 1
v 2 1
v 3 0
v 4 2
v 5 1
v 6 0
v 7 1
v 8 3
v 9 4
v 10 1
v 11 3
e 0 1 0
e 0 4 5
e 1 9 1
e 1 2 2
e 2 8 3
e 2 9 4
e 2 3 0
e 3 4 5
e 4 11 5
e 4 5 5
e 5 10 9
e 5 11 7
e 5 6 0
e 6 7 10
e 8 10 7
e 9 10 6
e 10 11 3
And when I use the homo on and print--enmu the result is
----------- Initial Matching ----------
1 0 0 
2 3 3 
5 6 6 
Initial Matching: 0.431ms
3 matches. 
So my questing is what the 1-0-0 stand for?

**Comment by xibosun** [comment]
> > Hi, the code does not explicitly store the set of all mappings from the query graph to the data graph. But one can run the code with `--print-enum on` to print all the mappings to the console.
> 
> Hi, could you please look after my test example ,I think here are something confused in it, My query graph is v 0 1 v 1 0 v 2 0 e 0 1 0 e 2 0 0 and data graph is v 0 0 v 1 1 v 2 1 v 3 0 v 4 2 v 5 1 v 6 0 v 7 1 v 8 3 v 9 4 v 10 1 v 11 3 e 0 1 0 e 0 4 5 e 1 9 1 e 1 2 2 e 2 8 3 e 2 9 4 e 2 3 0 e 3 4 5 e 4 11 5 e 4 5 5 e 5 10 9 e 5 11 7 e 5 6 0 e 6 7 10 e 8 10 7 e 9 10 6 e 10 11 3 And when I use the homo on and print--enmu the result is ----------- Initial Matching ---------- 1 0 0 2 3 3 5 6 6 Initial Matching: 0.431ms 3 matches. So my questing is what the 1-0-0 stand for?

Each line is a subgraph isomorphism result. And the first line 1 0 0 represents a result, where the query vertex 0 matches the data vertex 1, the query vertex 1 matches the data vertex 0, and the query vertex 2 matches the data vertex 0.

**Comment by Edison0521** [comment]
> > > Hi, the code does not explicitly store the set of all mappings from the query graph to the data graph. But one can run the code with `--print-enum on` to print all the mappings to the console.
> > 
> > 
> > Hi, could you please look after my test example ,I think here are something confused in it, My query graph is v 0 1 v 1 0 v 2 0 e 0 1 0 e 2 0 0 and data graph is v 0 0 v 1 1 v 2 1 v 3 0 v 4 2 v 5 1 v 6 0 v 7 1 v 8 3 v 9 4 v 10 1 v 11 3 e 0 1 0 e 0 4 5 e 1 9 1 e 1 2 2 e 2 8 3 e 2 9 4 e 2 3 0 e 3 4 5 e 4 11 5 e 4 5 5 e 5 10 9 e 5 11 7 e 5 6 0 e 6 7 10 e 8 10 7 e 9 10 6 e 10 11 3 And when I use the homo on and print--enmu the result is ----------- Initial Matching ---------- 1 0 0 2 3 3 5 6 6 Initial Matching: 0.431ms 3 matches. So my questing is what the 1-0-0 stand for?
> 
> Each line is a subgraph isomorphism result. And the first line 1 0 0 represents a result, where the query vertex 0 matches the data vertex 1, the query vertex 1 matches the data vertex 0, and the query vertex 2 matches the data vertex 0.



Thank you for your explanation, while I suppose that each line is a subgraph homomorphism, due to the command --homo on,is that right?

**Comment by xibosun** [comment]
> > > > Hi, the code does not explicitly store the set of all mappings from the query graph to the data graph. But one can run the code with `--print-enum on` to print all the mappings to the console.
> > > 
> > > 
> > > Hi, could you please look after my test example ,I think here are something confused in it, My query graph is v 0 1 v 1 0 v 2 0 e 0 1 0 e 2 0 0 and data graph is v 0 0 v 1 1 v 2 1 v 3 0 v 4 2 v 5 1 v 6 0 v 7 1 v 8 3 v 9 4 v 10 1 v 11 3 e 0 1 0 e 0 4 5 e 1 9 1 e 1 2 2 e 2 8 3 e 2 9 4 e 2 3 0 e 3 4 5 e 4 11 5 e 4 5 5 e 5 10 9 e 5 11 7 e 5 6 0 e 6 7 10 e 8 10 7 e 9 10 6 e 10 11 3 And when I use the homo on and print--enmu the result is ----------- Initial Matching ---------- 1 0 0 2 3 3 5 6 6 Initial Matching: 0.431ms 3 matches. So my questing is what the 1-0-0 stand for?
> > 
> > 
> > Each line is a subgraph isomorphism result. And the first line 1 0 0 represents a result, where the query vertex 0 matches the data vertex 1, the query vertex 1 matches the data vertex 0, and the query vertex 2 matches the data vertex 0.
> 
> Thank you for your explanation, while I suppose that each line is a subgraph homomorphism, due to the command --homo on,is that right?

Oh sorry. Right, it should be a homomorphism result rather than an isomorphism one.

**Comment by Edison0521** [comment]
> 
Alright, Thank you very much!
